### ISSUE TITLE
1.6 Version not working

### ISSUE THREAD

**Issue by BavovnaIsTaken** [appdictive/ADBRemoteConnect#3]
Yesterday (21/08/2017) after plugin updated to 1.6 version it stopped working. 
After I've downgraded it to 1.5 version - it works again.
    When I attempting to start 1.6 version it just blinks and closes immediately.
    Some of my PC, OS, AS specs:
Build: 2.3.3, AI-162.4069837, 20170606, 
AI-162.4069837, JRE 1.8.0_112-release-b06x64 JetBrains s.r.o, OS Linux(amd64) v4.4.0-89-generic unknown, screens 1366x768, 1920x1080

**Comment by JesperLR** [comment]
Hi

Are you running it from Android Studio?
Do you perhaps get a notification saying that adb is missing from the environment?

**Comment by BavovnaIsTaken** [comment]
Good afternoon!
Yes, I was running it from Android Studio. Where can I look for this notification? No message was shown as I remember.

**Comment by JesperLR** [comment]
It's within Android Studio - should be shown in right bottom corner, where other warning notifications might be shown. I introduced in 1.6 that a message would be shown if ADB is not available in the environment, but if 1.5 works for you this should not be the case.

Could I maybe get you to try running the 1.6 jar by itself from commandline with a regular 'java -jar' command, and tell me the output?
You should be able to find it in something similar to ".AndroidStudio2.3\config\plugins\ADBWiFiConnect\lib\ADBWiFiConnectGUI.jar" (at least this is the path on a Windows pc)

**Comment by yaroslavromanyuta** [comment]
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:945)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/css/StyleConverterImpl
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.jfoenix.controls.JFXButton$StyleableProperties.<clinit>(JFXButton.java:167)
	at com.jfoenix.controls.JFXButton.<init>(JFXButton.java:147)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:558)
	at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1019)
	at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:754)
	at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2722)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2552)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at dk.appdictive.adbwificonnect.ListViewCell.updateItem(ListViewCell.java:58)
	at dk.appdictive.adbwificonnect.ListViewCell.updateItem(ListViewCell.java:20)
	at javafx.controls/javafx.scene.control.ListCell.updateItem(ListCell.java:478)
	at javafx.controls/javafx.scene.control.ListCell.indexChanged(ListCell.java:337)
	at javafx.controls/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1708)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1692)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.getCellLength(VirtualFlow.java:1801)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.computeViewportOffset(VirtualFlow.java:2638)
	at javafx.controls/javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1245)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1226)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1233)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:590)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1773)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:394)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1098)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1186)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1201)
	at javafx.graphics/javafx.stage.Stage.show(Stage.java:276)
	at dk.appdictive.adbwificonnect.Main.start(Main.java:86)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.css.StyleConverterImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 56 more
Exception running application dk.appdictive.adbwificonnect.Main

**Comment by JesperLR** [comment]
Hi yaroslavromanyuta!
Could it be that you are using something older than JDK 8 when running the jar?

**Comment by BavovnaIsTaken** [comment]
Please, find my error via link:
https://pastebin.com/fCybutb3

It seems to be that I've got JDK 1.8 (/usr/lib/jvm/java-1.8.0-openjdk-amd64/...)

**Comment by JesperLR** [comment]
Ok, so it definitely looks like it's got something to do with either using css in JavaFX or the new lib I included for material looking buttons. Will have to test it without either one to know for sure.

What distribution of Linux are you running it on? Would you maybe be willing to test it if I produce a couple of jars - one without css and one without the material javafx lib?

**Comment by BavovnaIsTaken** [comment]
I'm using Ubuntu 16.04. Yes, I can test a couple of jars (:

**Comment by JesperLR** [comment]
Sweet!

I've attached two different attempts here, one without css styling and one without the material look library - much appreciated if you will give it a try and report back :)


[ADBWiFiConnectGUI_test.zip](https://github.com/appdictive/ADBWiFiConnect/files/1260149/ADBWiFiConnectGUI_test.zip)

**Comment by yaroslavromanyuta** [comment]
NoMaterial version works fine.

**Comment by JesperLR** [comment]
Cool - thanks mate!
I've submitted a new version (1.7) without the material lib (JFoenix) that should work for you as well then, usually takes a couple of days before it's approved for release, then I'll close issue when it's out :)

**Comment by BavovnaIsTaken** [comment]
Yep, NoMaterial works good as for me too.
When trying to start NoCSS - I've got an error: https://pastebin.com/LGRh7QhQ

So.. waiting for v1.7 (:

**Comment by JesperLR** [comment]
Version 1.7 has been released and should fix this issue.

Thanks for the assistance! :)
